language: python

python:
  - 2.7

install:
  - pip install codecov
  - pip install pyactor
  - pip install coverage

ignore:
  - /Files/*
  - Master.py
  - FileHandler.py
  - Wordcount.py
  - CountingWords.py

script:
  - python -m SimpleHTTPServer &
  - python -m coverage run test.py

after_success:
    - bash <(curl -s https://codecov.io/bash)