language: python

python:
  - 2.7

install:
  - pip install pyactor
  cd $TRAVIS_BUILD_DIR/InputFile
  - python -m SimpleHTTPServer &
  cd ..
  - python Registry.py 127.0.0.2 &
  - python Worker.py 127.0.0.3:6008 127.0.0.2:6000 travis-env &
  - python Exemple.py

script: